---
title: "R_script"
author: "yye24@jh.edu"
date: "2025-02-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load required packages
```{r}
library(ChIPseeker)
library(clusterProfiler)
library(DESeq2)
library(GenomicFeatures)
library(GenomicAlignments)
library(org.Hs.eg.db)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(dplyr)
```

### Import narrowPeak file: /path/to/file/all_peaks.narrowPeak, and annotate the peaks
```{r}
Txdb.hg38 <- TxDb.Hsapiens.UCSC.hg38.knownGene
all_peaks_plus <- subset(all_peaks, all_peaks$V6 == "+")
all_peaks_minus <- subset(all_peaks, all_peaks$V6 == "-")
all_peaks_plus.gr <- GRanges(seqnames=all_peaks_plus$V1, ranges=IRanges(all_peaks_plus$V2, all_peaks_plus$V3), strand="+", mcols=data.frame(peakID=all_peaks$V4))
all_peaks_minus.gr <- GRanges(seqnames=all_peaks_minus$V1, ranges=IRanges(all_peaks_minus$V2, all_peaks_minus$V3), strand="-", mcols=data.frame(peakID=all_peaks_minus$V4))
all_peaks.gr <- c(all_peaks_plus.gr, all_peaks_minus.gr)
all_peaks.bed.annot = annotatePeak(all_peaks.gr, tssRegion=c(-3000, 3000), TxDb=Txdb.hg38, annoDb="org.Hs.eg.db")
annot_all_peaks = as.data.frame(all_peaks.bed.annot)
```

### Calculate the enrichment score: IP/input
## import raw counts data: /path/to/file/Peak_counts.txt
```{r}
sample_info <- data.frame(
  row.names = colnames(Peak_counts,
  condition = gsub("_.*","", names(Peak_counts)),
  group = factor(c("control", "control", "control", "control", "control", "control", "treatment", "treatment", "treatment", "treatment", "treatment", "treatment"),
  type = factor(c("Input", "Input", "Input", "IP", "IP", "IP", "Input", "Input", "Input", "IP", "IP", "IP"))
)
sample_info$group <- relevel(sample_info$group, ref = "control")
sample_info$type <- relevel(sample_info$type, ref = "Input")
dds <- DESeqDataSetFromMatrix(countData = Peak_counts, colData = sample_info, design = ~ group + type)
# subset dataset
dds_ctrl <- dds[, dds$group == "control"]
dds_ctrl$group <- droplevels(dds_ctrl$group)
dds_ctrl$type <- droplevels(dds_ctrl$type)
dds_ctrl$type <- relevel(dds_ctrl$type, ref = "Input")
design(dds_ctrl) <- ~ type  
# Run DESeq on the subsetted dataset
dds_ctrl <- DESeq(dds_ctrl)
deseq2_ctrl_ip_vs_input <- results(dds_ctrl, contrast = c("type", "IP", "Input"))
```
